baseURL = "/"
languageCode = "en-us"
title = "Black Mesa: Blue Shift theme"
DefaultContentLanguage = "en"

[taxonomies]
tag = "tags"

[languages.en]
languageName = "En"
weight = 1
	[[languages.en.menu.main]]
	name = "Blog"
	url = "/blog"
	weight = 1
	[[languages.en.menu.blog]]
	name = "Home"
	url = "/"
	weight = 1
	[[languages.en.menu.blog]]
	name = "Blog"
	url = "/blog"
	weight = 2

